language: python
python:
  - "3.9"
# command to install dependencies
# install:
  # - pip install -r requirements.txt
# command to run tests
script:
  - sudo apt-get update
  - sudo apt-get install gputils
  - python3 tests.py
